### ISSUE TITLE
emoji 👍 from matrix side is not bridged

### ISSUE THREAD

**Issue by zhubonan** [mautrix/slack#15]
The 👍  reaction cannot be set in portal rooms and an error of the short code not found is shown.

![image](https://user-images.githubusercontent.com/33688599/215843571-bf6c9c51-d8e0-4af4-9fe2-e6fc57ca74c8.png)

Looking at the log I see this:
![image](https://user-images.githubusercontent.com/33688599/215844622-2f876574-b4d7-45f1-b657-012aa5724c66.png)

Seems that the recorded 👍 in the message is different? If I copy this 👍  and paste it, it becsomes smaller, maybe there are different kinds of👍?

**Comment by slagiewka** [comment]
Using the latest Docker build from 17.07 ([cb748db](https://github.com/mautrix/slack/commit/cb748dbc825f3aa310408f215470aea67eb736bb)) I can't reproduce this issue.
