### ISSUE TITLE
Long URLs aren't bridged correctly

### ISSUE THREAD

**Issue by ptman** [mautrix/slack#16]
E.g. 

    https://www.kauppalehti.fi/uutiset/supercell-peraa-asennemuutosta-yrityksiin-osaajat-lahtevat-jos-puoliso-ei-saa-toita/3b0779a2-87fb-4968-b3a4-78b49938543e

was bridged as:

    https://www.kauppalehti.fi/uutiset/supercell-peraa-asennemuutosta-yrityksiin-osaajat-l[...]s-puoliso-ei-saa-toita/3b0779a2-87fb-4968-b3a4-78b49938543e

**Comment by slagiewka** [comment]
I used the link of yours and I can't reproduce 

![image](https://github.com/mautrix/slack/assets/11974489/13310efb-dc9f-40b1-870c-cb5613641a26)

I'm using the latest docker build from 17.07: cb748db

I think the edit is only because there's some automatic reformatting, so it might be irrelevant:
```json
{
  "content": {
    "msgtype": "m.text",
    "body": "* https://www.kauppalehti.fi/uutiset/supercell-peraa-asennemuutosta-yrityksiin-osaajat-lahtevat-jos-puoliso-ei-saa-toita/3b0779a2-87fb-4968-b3a4-78b49938543e",
    "format": "org.matrix.custom.html",
    "formatted_body": "* <a href=\"https://www.kauppalehti.fi/uutiset/supercell-peraa-asennemuutosta-yrityksiin-osaajat-lahtevat-jos-puoliso-ei-saa-toita/3b0779a2-87fb-4968-b3a4-78b49938543e\">https://www.kauppalehti.fi/uutiset/supercell-peraa-asennemuutosta-yrityksiin-osaajat-lahtevat-jos-puoliso-ei-saa-toita/3b0779a2-87fb-4968-b3a4-78b49938543e</a>",
    "m.new_content": {
      "msgtype": "m.text",
      "body": "https://www.kauppalehti.fi/uutiset/supercell-peraa-asennemuutosta-yrityksiin-osaajat-lahtevat-jos-puoliso-ei-saa-toita/3b0779a2-87fb-4968-b3a4-78b49938543e",
      "format": "org.matrix.custom.html",
      "formatted_body": "<a href=\"https://www.kauppalehti.fi/uutiset/supercell-peraa-asennemuutosta-yrityksiin-osaajat-lahtevat-jos-puoliso-ei-saa-toita/3b0779a2-87fb-4968-b3a4-78b49938543e\">https://www.kauppalehti.fi/uutiset/supercell-peraa-asennemuutosta-yrityksiin-osaajat-lahtevat-jos-puoliso-ei-saa-toita/3b0779a2-87fb-4968-b3a4-78b49938543e</a>"
    },
    "m.relates_to": {
      "rel_type": "m.replace",
      "event_id": "$hITLNIbrFFbON-EjlfTh7ideIIm3K2fBKnCtLR0rGZg"
    }
  },
}
```

**Comment by ptman** [comment]
Great if it works. Did you try both directions?

**Comment by slagiewka** [comment]
> Did you try both directions?

I did, just now. Looks OK to me. This time no edits visible. That might be due to Slack no longer "unfurling" the preview on their side (as it was already added to previous messages with myself).

I think I've seen the approach to shorten _display_ of links on Slack when they're to long, but actual links are still correct. Maybe this issue was:
* only presentation, not actual link

OR
* bridge taking the (shortened) text and treating it as a link

**Comment by twouters** [comment]
Not sure why but I'm still seeing this issue if I paste the url from the issue report in a DM to myself (on Slack).

The bridge even seems to be looping on this message as the edits keep piling up on Matrix:

![Screenshot from 2023-08-02 13-36-59](https://github.com/mautrix/slack/assets/170895/5431de14-8455-4ee3-a7c3-487601c032fa)

**Comment by twouters** [comment]
@ptman i think this needs to be reopened

**Comment by slagiewka** [comment]
Another round of testing. This time on a different computer (with macOS).

![image](https://github.com/mautrix/slack/assets/11974489/0e353553-cbc4-4d2f-afac-e885ba16810a)


When I'm pasting into Slack (web in Firefox or native app), the link is already `[...]`-fied even before I send it. Then I see that effect in Matrix (Element). But the link is still properly working (as demonstrated above).
