### ISSUE TITLE
Some room names keep changing to `#` name only and back and forth

### ISSUE THREAD

**Issue by erAck** [mautrix/slack#17]
I have two rooms with name `#` only (well, sometimes), and only getting state events not messages. Apparently these "empty" rooms are a leftover from when I logged out of a Slack session they were initially synced from, and duplicates of newly synced same channels with a different room ID. The rooms keep changing name like this:

```
Wednesday, 10:40, Slack bridge bot changed the room name from #announce to #.
Wednesday, 10:40, Slack bridge bot changed the topic to "".
Wednesday, 16:02, Slack bridge bot changed the room name from # to #announce.
Wednesday, 16:02, Slack bridge bot changed the topic to "Description: Welcome Channel Updates".
Wednesday, 21:02, Slack bridge bot changed the room name from #announce-global to #.
Wednesday, 21:02, Slack bridge bot changed the topic to "".
Wednesday, 21:42, Slack bridge bot changed the room name from # to #announce.
Wednesday, 21:42, Slack bridge bot changed the topic to "Description: Welcome Channel Updates".
```

Such room name changes may also happen for the not abandoned but lively synced room if it bridges to the same Slack channel as the abandoned room exposing the behaviour.

**Comment by yawks** [comment]
I had the same issue, my pull request https://github.com/mautrix/slack/pull/23 fixes the problem on instance

**Comment by vrutkovs** [comment]
Perhaps https://github.com/mautrix/slack/commit/7e379049f1c0be2bb6d0b38eaff331f2eb000591 fixes it?
