### ISSUE TITLE
Errors connecting to an enterprise Slack account (enterprise_is_restricted)

### ISSUE THREAD

**Issue by evmcl** [mautrix/slack#46]
Attempts to get the slackbot to login fail.

Using `login-token`, it returns: "Failed to log in with token: enterprise_is_restricted"

For `login-password`, it returns: "teams that use Single Sign On are not currently supported"

In the [discussion room](https://matrix.to/#/#slack:maunium.net) Tulir said it, "looks like enterprise_is_restricted might be some recent api change" and cited [issue 910 for wee-slack](https://github.com/wee-slack/wee-slack/issues/910) as a reference.

**Comment by niebloomj** [comment]
I imagine this is intentional as companies don't want slack to allow employees to exfill data

**Comment by tulir** [comment]
That isn't really relevant. If the slack web app works then the bridge can't work, so since the bridge doesn't work, it's just doing something slightly wrong.
