### ISSUE TITLE
Unable to active double puppeting

### ISSUE THREAD

**Issue by wapsi** [mautrix/slack#5]
I'm unable to active the double puppeting. With all other bridges I'm using the "login-matrix <my Matrix access token>" command works just fine, but with this bridge the bot just throws: "Didn't get a ghost :(" message. I have tried multiple different access tokens (tried to generate couple of new ones as well, so I'm 100% certain those are valid access tokens), but none of them works.

In the debug logs there's nothing interesting: the login-matrix received by the bridge and then it immediately responds with that "Didn't get a ghost :(" message:
```
[Oct  4, 2022 17:52:35] [CommandProcessor/DEBUG] @foouser:foo.bar sent "login-matrix xxx" in !yyy:foo.bar
[Oct  4, 2022 17:52:35] [Matrix/Bot/DEBUG] req #19: PUT http://localhost:8008/_matrix/client/v3/rooms/%21xxx:foo.bar/send/m.room.message/mautrix-go_123412341234_3?user_id=%40slackbot%3Afoo.bar {"msgtype":"m.notice","body":"Didn't get a ghost :("}
```
How can I debug this issue, or do you have any idea where the problem could it be? In the Synapse INFO level logs, there are only 200 OK responses to the as-sender-slack when I'm executing the "login-matrix xxx" command, no errors.

I'm following the instructions from here: https://docs.mau.fi/bridges/general/double-puppeting.html

**Comment by petermolnar** [comment]
Same here, but I have to add this is said at https://docs.mau.fi/bridges/general/double-puppeting.html 
`N.B. This method is not currently supported in mautrix-imessage and mautrix-slack.` on

**Comment by Konubinix** [comment]
I :+1:   on this issue. I would love to have double pupetting here

**Comment by niebloomj** [comment]
Double puppeting not working for me either.

**Comment by niebloomj** [comment]
Can we get a list of items we need to complete to fix this issue? I'd like to track our progress towards this goal.

**Comment by tom-kuca** [comment]
I look around, the error message comes from [mautrix/go](https://github.com/mautrix/go/blob/cbd13347246359e3819ac12ee2576788bce36705/bridge/commands/doublepuppet.go#L29). It's printed when `GetIGhost()` returns nil. For slack, the implementation is commented out:
https://github.com/mautrix/slack/blob/a9ba2f9249bdc5df69a1349122d1769e7e48c9e1/user.go#L85-L95

It was commented 2 years ago in commit https://github.com/mautrix/slack/commit/4af303de1492ce65302954a5a9a27efad3c442d0 (*Basic login and logout support for multiple teams*).

**Comment by niebloomj** [comment]
My guess is that since this is the only bridge that supports multiple logins, double puppeting didn't work as expected and needs to be reimplemented for a bridge that has multiple logins.

**Comment by nolimbsdotdev** [comment]
This behaviour is expected. See https://docs.mau.fi/bridges/general/double-puppeting.html
```
**Appservice method (new)**
 N.B. This method is not supported in the legacy (Python) Signal bridge nor the current iMessage and Slack bridges. You can use the alternative methods like shared secret login documented below (https://docs.mau.fi/bridges/general/double-puppeting.html#shared-secret-method-legacy-synapse-only) for those.
```

**Comment by niebloomj** [comment]
You mean it's a known bug and not that it's expected, right? Because I have no way to enable double puppeting for Slack on my dendrite server because of this so I wouldn't call that "expected" behavior, but rather, a known bug.
