### ISSUE TITLE
legacy bridge config detected error

### ISSUE THREAD

**Issue by cyberb** [mautrix/slack#56]
I am getting this error after the upgrade to latest:
```
Legacy bridge config detected, but hacky network config migrator is not set
```

Is there a way to migrate config or is it not ready yet and I should move back to last stable version?

**Comment by tulir** [comment]
Migrating legacy configs isn't supported, not sure if it will be. You can make a new config (`mautrix-slack -c example.yaml -e` can be used to generate the example config)
