### ISSUE TITLE
Room not added to a space

### ISSUE THREAD

**Issue by dimm0** [mautrix/slack#57]
A newly added room appears under "others" and is not integrated into the space with all other rooms.

I see the https://github.com/mautrix/discord/issues/65 ticket, is there any similar command for this bridge?

**Comment by tulir** [comment]
Missing info like logs and bridge version

**Comment by tulir** [comment]
Was it just rooms created on the old version, or did a new room on the new version also not get added to the space?

**Comment by dimm0** [comment]
I had the older version running for 2 weeks.
I went to slack and added the new room to my slack account. The bot immediately invited me to the room in matrix. I joined the room, but noticed it's not added to the space.
I restarted the bridge pod, and it complained I need to fix the config. I did that, now the bridge is happy again, but room is still not in the space.
I left the room, made the bot invite me again, joined the room again, but it's still out of the space. Currently it's the new version running.

I can try to make the bot del the room and recreate I guess?

**Comment by tulir** [comment]
`!slack delete-portal` can be used to delete rooms, or you can clear the `parent_id` and `in_space` columns in the `portal` table and restart the bridge.

**Comment by dimm0** [comment]
That worked, thanks! 🎉

**Comment by niebloomj** [comment]
Which solution worked?

**Comment by dimm0** [comment]
`!slack delete-portal` in the room with the problem
