### ISSUE TITLE
Minor bug:  Message reactions made through Matrix are duplicated on the Matrix side

### ISSUE THREAD

**Issue by mcronce** [mautrix/slack#6]
Everything looks fine when anybody (myself included) reacts to a message in Slack, but when I react to a message in Matrix, I get an "extra" reaction on the Matrix side from the Matrix user that represents my Slack user

~I do have double puppeting enabled, in case that's relevant~

I'm sure there are higher priority things.  :)

**Comment by vurpo** [comment]
I've seen a similar issue happen with other kinds of messages on a different server, but I haven't started debugging what may cause it yet.
